"""Publish the big catalog files to the repo's `catalog-data` branch.

The per-set card lists, name shards, photo fingerprints and parallel colours (data/catalog/remote) plus the raw
price-guide pulls they are built from (data/raw) are hundreds of MB and change on every rebuild. Keeping them in
the code branch made every rebuild add hundreds of MB of history. Instead they go to `catalog-data`, a branch
that always holds exactly one commit (replaced on each publish), and the apps download from
https://raw.githubusercontent.com/<owner>/<repo>/catalog-data/remote/... (see REMOTE in app/src/core/catalog.ts
and DATA_URL in streamlit/core/catalog.py).

    python data/build_catalog.py && python data/publish_catalog.py

To rebuild somewhere else, get the raw pulls back first:  python data/publish_catalog.py --fetch-raw
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
BRANCH = "catalog-data"


def git(*args, cwd=None, check=True):
    return subprocess.run(["git", *args], cwd=cwd, check=check, text=True, capture_output=True)


def origin() -> str:
    return git("remote", "get-url", "origin", cwd=REPO).stdout.strip()


def publish() -> None:
    remote = os.path.join(HERE, "catalog", "remote")
    if not os.path.exists(os.path.join(remote, "index.json")):
        sys.exit("Build the catalog first (data/build_catalog.py)")
    with tempfile.TemporaryDirectory() as tmp:
        shutil.copytree(remote, os.path.join(tmp, "remote"))
        raw = os.path.join(HERE, "raw")
        if os.path.isdir(raw):
            shutil.copytree(raw, os.path.join(tmp, "raw"))
        with open(os.path.join(tmp, "README.md"), "w") as fh:
            fh.write("Slab Scout catalog data (generated by data/publish_catalog.py on the code branch; replaced on every publish).\n")
        big = [os.path.join(dp, f) for dp, _, fs in os.walk(tmp) for f in fs if os.path.getsize(os.path.join(dp, f)) > 95e6]
        if big:
            sys.exit(f"Files over GitHub's 100 MB limit: {big}")
        git("init", "-q", "-b", BRANCH, cwd=tmp)
        git("add", "-A", cwd=tmp)
        name = git("config", "user.name", cwd=REPO, check=False).stdout.strip() or "Kingatlasing"
        mail = git("config", "user.email", cwd=REPO, check=False).stdout.strip() or "aapara98@gmail.com"
        git("-c", f"user.name={name}", "-c", f"user.email={mail}", "commit", "-q", "-m", "Catalog data", cwd=tmp)
        git("remote", "add", "origin", origin(), cwd=tmp)
        r = git("push", "-q", "-f", "origin", BRANCH, cwd=tmp, check=False)
        if r.returncode:
            sys.exit(r.stderr)
    print(f"Published data/catalog/remote + data/raw to the {BRANCH} branch")


def fetch_raw() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        r = git("clone", "-q", "--depth", "1", "-b", BRANCH, origin(), tmp, check=False)
        if r.returncode:
            sys.exit(r.stderr)
        src = os.path.join(tmp, "raw")
        dst = os.path.join(HERE, "raw")
        os.makedirs(dst, exist_ok=True)
        for f in os.listdir(src):
            if not os.path.exists(os.path.join(dst, f)):
                shutil.copy2(os.path.join(src, f), os.path.join(dst, f))
    print("Raw pulls restored to data/raw")


if __name__ == "__main__":
    fetch_raw() if "--fetch-raw" in sys.argv else publish()
