"""Serialize a voxel model to formats people can actually do something with."""

from __future__ import annotations

import json

from .palette import PALETTE

Voxel = tuple[int, int, int, str]

_BLOCK_BY_HEX = {s.hex: s.block for s in PALETTE}


def to_json(voxels: list[Voxel]) -> str:
    return json.dumps(
        [{"x": x, "y": y, "z": z, "color": c} for x, y, z, c in voxels],
        indent=2,
    )


def to_obj(voxels: list[Voxel]) -> str:
    """A naive (unmerged) cube-per-voxel OBJ mesh, with matching MTL colors."""
    lines_obj = ["mtllib model.mtl", ""]
    lines_mtl = []
    seen_colors: dict[str, str] = {}
    vert_offset = 0

    # unit cube, 8 verts, 6 quad faces
    cube_verts = [
        (0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
        (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1),
    ]
    cube_faces = [
        (1, 2, 3, 4), (5, 8, 7, 6),
        (1, 5, 6, 2), (2, 6, 7, 3),
        (3, 7, 8, 4), (4, 8, 5, 1),
    ]

    for x, y, z, color in voxels:
        if color not in seen_colors:
            mat_name = f"c{len(seen_colors)}"
            seen_colors[color] = mat_name
            r = int(color[1:3], 16) / 255
            g = int(color[3:5], 16) / 255
            b = int(color[5:7], 16) / 255
            lines_mtl.append(f"newmtl {mat_name}\nKd {r:.3f} {g:.3f} {b:.3f}\n")
        mat_name = seen_colors[color]
        lines_obj.append(f"usemtl {mat_name}")
        for vx, vy, vz in cube_verts:
            lines_obj.append(f"v {x + vx} {y + vy} {z + vz}")
        for f in cube_faces:
            idx = tuple(vert_offset + i for i in f)
            lines_obj.append("f " + " ".join(str(i) for i in idx))
        vert_offset += 8

    return "\n".join(lines_obj), "\n".join(lines_mtl)


def mesh_to_obj(vertices: list[tuple[float, float, float]], faces: list[tuple[int, int, int]],
                 color: str = "#E0AC85") -> tuple[str, str]:
    """A real polygon-mesh OBJ (actual vertices/faces from `mesh_face.py`,
    not one cube per voxel like `to_obj`) — this is what lets the mesh
    tier's output open correctly in any 3D modeling tool as a smooth
    faceted sculpt rather than a pile of unioned cubes. Returns
    (obj_text, mtl_text), matching `to_obj`'s return shape."""
    r = int(color[1:3], 16) / 255
    g = int(color[3:5], 16) / 255
    b = int(color[5:7], 16) / 255
    mtl = f"newmtl mesh\nKd {r:.3f} {g:.3f} {b:.3f}\n"
    lines = ["mtllib model.mtl", "", "usemtl mesh"]
    for x, y, z in vertices:
        lines.append(f"v {x:.5f} {y:.5f} {z:.5f}")
    for a, b_, c in faces:
        lines.append(f"f {a + 1} {b_ + 1} {c + 1}")  # OBJ indices are 1-based
    return "\n".join(lines), mtl


def to_mcfunction(voxels: list[Voxel], origin_note: str = "~ ~ ~") -> str:
    """Emit `/fill` commands (run-length-encoded along x) that build the
    model out of real Minecraft blocks, relative to wherever it's run from.

    Usage: save as data/voxelcraft/functions/build.mcfunction in a datapack,
    /reload, stand where you want voxel (0,0,0) to land, then
    /function voxelcraft:build
    """
    # group by (y, z, block) and run-length-encode contiguous x spans
    by_row: dict[tuple[int, int, str], list[int]] = {}
    for x, y, z, color in voxels:
        block = _BLOCK_BY_HEX.get(color, "minecraft:stone")
        by_row.setdefault((y, z, block), []).append(x)

    commands = [
        "# Generated by VoxelCraft — run this standing where the model's",
        "# origin (0,0,0) should appear.",
    ]
    for (y, z, block), xs in sorted(by_row.items()):
        xs.sort()
        run_start = xs[0]
        prev = xs[0]
        for cur in xs[1:] + [None]:
            if cur is not None and cur == prev + 1:
                prev = cur
                continue
            if run_start == prev:
                commands.append(f"fill ~{run_start} ~{y} ~{z} ~{run_start} ~{y} ~{z} {block}")
            else:
                commands.append(f"fill ~{run_start} ~{y} ~{z} ~{prev} ~{y} ~{z} {block}")
            if cur is not None:
                run_start = cur
                prev = cur
    return "\n".join(commands)
